language: node_js
node_js:
  - "6.2"
  - "4.4"
install:
  - npm config set spin=false
  - npm install -g coveralls
  - npm install

script:
  - npm test
  - npm run lint
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false
